version: "3.8"

services:
  app:
    build: .
    container_name: discodeit-app
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/discodeit
      SPRING_DATASOURCE_USERNAME: discodeit_user
      SPRING_DATASOURCE_PASSWORD: discodeit1234
      JVM_OPTS: ${JVM_OPTS}
    depends_on:
      - db
    volumes:
      - app-data:/app/storage

  db:
    image: postgres:15
    container_name: discodeit-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  app-data:
  db-data: